using UnityEngine;
using UnityEditor;
using System.IO;

public class AAAMapBaker : EditorWindow
{
    [MenuItem("Tools/AAA Map Baker")]
    public static void ShowWindow()
    {
        GetWindow<AAAMapBaker>("Map Baker");
    }

    void OnGUI()
    {
        GUILayout.Label("AAA Minimap Baker", EditorStyles.boldLabel);
        GUILayout.Label("This tool works exactly like the map generators in GTA or Cyberpunk!", EditorStyles.wordWrappedLabel);
        GUILayout.Space(10);
        GUILayout.Label("1. Make sure your 'Picture Bottom Left Corner' and 'Picture Top Right Corner' are assigned in your Minimap script.", EditorStyles.wordWrappedLabel);
        GUILayout.Label("2. Move those two empty objects in your 3D Scene to tightly frame your race track.", EditorStyles.wordWrappedLabel);
        GUILayout.Space(10);

        if (GUILayout.Button("Bake Ultra-HD Map Picture", GUILayout.Height(50)))
        {
            BakeMap();
        }
    }

    void BakeMap()
    {
        Minimap minimap = FindObjectOfType<Minimap>();
        if (minimap == null)
        {
            Debug.LogError("[Map Baker] Couldn't find a Minimap in your UI! Make sure the Minimap script is in your scene.");
            return;
        }

        // --- 1. AUTO-SCAN FOR ROAD BOUNDS ---
        Renderer[] allRenderers = FindObjectsOfType<Renderer>();
        Bounds roadBounds = new Bounds(Vector3.zero, Vector3.zero);
        bool foundRoad = false;

        foreach (Renderer r in allRenderers)
        {
            // Automatically find all meshes generated by RoadArchitect
            if (r.transform.root.name.Contains("RoadArchitect") || r.gameObject.name.Contains("Road"))
            {
                if (!foundRoad)
                {
                    roadBounds = new Bounds(r.bounds.center, Vector3.zero);
                    foundRoad = true;
                }
                roadBounds.Encapsulate(r.bounds);
            }
        }

        if (!foundRoad)
        {
            Debug.LogError("[Map Baker] Couldn't find any RoadArchitect meshes to calculate the map size! Ensure your roads are generated.");
            return;
        }

        // Add a small 10% margin so the road isn't touching the exact edge of the picture
        roadBounds.Expand(new Vector3(roadBounds.size.x * 0.1f, 0, roadBounds.size.z * 0.1f));

        Vector3 center = roadBounds.center;
        float width = roadBounds.size.x;
        float height = roadBounds.size.z;
        float orthoSize = Mathf.Max(width, height) / 2f;

        // --- 2. BAKE ULTRA-HD MAP ---
        GameObject camObj = new GameObject("BakerCamera");
        Camera cam = camObj.AddComponent<Camera>();
        cam.orthographic = true;
        cam.orthographicSize = orthoSize;
        cam.transform.position = new Vector3(center.x, 1000f, center.z);
        cam.transform.rotation = Quaternion.Euler(90, 0, 0);
        cam.clearFlags = CameraClearFlags.Color;
        cam.backgroundColor = new Color(0.1f, 0.1f, 0.1f, 1f);

        int res = 4096;
        RenderTexture rt = new RenderTexture(res, res, 24);
        cam.targetTexture = rt;
        cam.Render();

        RenderTexture.active = rt;
        Texture2D tex = new Texture2D(res, res, TextureFormat.RGB24, false);
        tex.ReadPixels(new Rect(0, 0, res, res), 0, 0);
        tex.Apply();

        byte[] bytes = tex.EncodeToPNG();
        string relativePath = "Assets/MinimapBaked_HD.png";
        string absolutePath = Application.dataPath + "/MinimapBaked_HD.png";
        File.WriteAllBytes(absolutePath, bytes);

        RenderTexture.active = null;
        cam.targetTexture = null;
        DestroyImmediate(camObj);

        AssetDatabase.ImportAsset(relativePath);
        TextureImporter importer = (TextureImporter)AssetImporter.GetAtPath(relativePath);
        if (importer != null)
        {
            importer.textureType = TextureImporterType.Sprite;
            importer.SaveAndReimport();
        }

        // --- 3. AUTO-CALIBRATE MINIMAP.CS ---
        minimap.mapWorldCenter = new Vector2(center.x, center.z);
        
        // World width is 2x the Orthographic Size of the camera
        float worldWidth = orthoSize * 2f;
        
        // Calculate the perfect scale based on the user's MapImage RectTransform width!
        float actualUIWidth = minimap.mapImage.rect.width * minimap.mapImage.localScale.x; 
        minimap.mapScale = actualUIWidth / worldWidth;

        EditorUtility.SetDirty(minimap);

        Debug.Log($"[Map Baker] SUCCESS! Auto-scanned {roadBounds.size.x}x{roadBounds.size.z} meters of road. Saved to 'Assets/MinimapBaked_HD.png'. Minimap math is 100% calibrated!");
    }
}
